AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Resources for {{ cookiecutter.project_name }}"
Parameters:
  AppGroup:
    Type: "String"
    Default: {{ cookiecutter.project_app_group }}
  Environment:
    Type: "String"
    AllowedValues:
      - "development"
      - "testing"
      - "acceptance"
      - "production"
    Default: "development"
    ConstraintDescription: "Must be one of the values from the list."
    Description: "Environment in which resources are deployed."
  Region:
    Description: "Specify the region"
    Type: "String"
    Default: "eu-west-1"
    AllowedValues:
      - "eu-west-1"
Resources:
  Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code/
      FunctionName: !Sub "${AppGroup}-function" # make sure to change the functionname
      Runtime: "nodejs8.10"
      Handler: index.hello
      Timeout: 300
      Role: !ImportValue "iam-lambda-basic-execution-role-arn" # default role; aws-coolblue
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
